### PR TITLE
add docker/compose configuration

### PR DESCRIPTION
**Pull request by dunn**
I was fiddling around with a local installation and before I knew it this happened.

Everything seems to work in a local docker environment; when I tried deploying it I sometimes saw errors with the first created poll closing automatically, but that might be something with my setup.

Of course I completely understand if this isn't something you're interesting in carrying in the codebase.

### CODE REVIEW

**Comment by andrewcmyers** [comment]
I like the shell script cleanup you are doing a lot but want to think more about the docker idea. Could we stage this into two PRs? Thanks!

**Comment by dunn** [comment]
sure thing; opened https://github.com/andrewcmyers/civs/pull/43

**Comment by jjasghar** [comment]
nice @dunn thanks for this, i was totally about to run with it...maybe I'll make a k8s deployment off this if it gets published :)

**Comment by dunn** [comment]
@jjasghar i actually have one of those as well: https://computer.crimes.consulting/cat/civs/-/tree/trunk/chart

but currently i'm running into an issue where it's allowing duplicate votes and i'm not sure why

**Comment by jjasghar** [comment]
Nice!

**Comment by andrewcmyers** [comment]
This PR needs to be redone at this point to be adopted.

**Pull request closed without merging**
